version: '3'
services:
    flask:
        build: '.'
        ports:
            - '5000:5000'
        stop_signal: SIGTERM
        volumes: 
            - './:/app:ro'
        environment: 
            - 'DEBUG=True'

    sqldb:
        image: mariadb
        environment: 
            - 'MYSQL_ROOT_PASSWORD=root-password'
            - 'MYSQL_USER=db-user'
            - 'MYSQL_PASSWORD=db-password'